### ISSUE TITLE
Edge browser functionality

### ISSUE THREAD

**Issue by spriggsha** [Financial-Times/o-overlay#90] opened 2015-08-13 09:43 UTC
Did a quick sanity check using the new Microsoft Edge browser, and it appears that the overlay buttons in the demos don't do anything.  No overlay, no console error.

I've got a Win10 VM set up for testing if it's needed.  Let me know and I can send VNC connection details.

**Comment by kaelig** [comment] 2015-08-13 10:33
Thank you very much for reporting, @spriggsha.

@AlbertoElias can you have a look into it?

**Comment by AlbertoElias** [comment] 2015-08-13 10:53
Yup, I had already talked with @spriggsha about it. Will check it out in the VM later today or tomorrow

**Comment by patrickkettner** [comment] 2015-08-14 00:19
There actually is an error, its just not happening on click but on load (and F12 tools doesn't show it unless you already have them open when loading the page).

The probkem is that the `.matches` method doesn't exist on the element being tested. The matchesSelector fallback does work, however. I created a PR on the o-dom repo to fix this.

**Comment by AlbertoElias** [comment] 2015-08-14 09:12
@patrickkettner Thanks a lot for your help. We do rely on the polyfill service for these things though. I've checked, and the issue is that the polyfill for matches isn't being served as Edge support in the polyfill service is still in qa and will be released next week. I've made sure it does with this new release :)

**Comment by patrickkettner** [comment] 2015-08-14 13:30
ah - should have assumed as much

cheers!

**Comment by onishiweb** [comment] 2016-03-15 14:59
Should we test this again to make sure it's fixed, or can we assume this is all good after the release.

**Comment by AlbertoElias** [comment] 2016-03-15 15:08
If you'd like to retest, but it should be good

**Comment by onishiweb** [comment] 2016-03-15 16:20
Yep, tested and all good. Closing.

**Closed by onishiweb** 2016-03-15 16:20 UTC
Labels: bug
