### ISSUE TITLE
Page scroll on Safari

### ISSUE THREAD

**Issue by roland-vachter** [Financial-Times/o-overlay#52] opened 2015-02-05 11:56 UTC
When opening the overlay, page scrolls to bottom
Affects:
- Safari 5
- Safari 6

**Comment by Vallach** [comment] 2015-02-09 12:36
Affects:
- all Safari versions from 5 to 8 (not tested versions older than 5)
- Mobile Safari 8.1.3

**Comment by AlbertoElias** [comment] 2015-03-02 17:14
I've tried seeing this in Safari 8 and couldn't reproduce, could you send a test case please?

**Comment by Vallach** [comment] 2015-03-03 12:06
Sent you detailed steps to reproduce and video of issue via email

**Comment by AlbertoElias** [comment] 2015-03-10 16:18
Speaking with @roland-vachter he suggested it might be due to an input having autofocus and he was right. Will try to find a work around for this

**Comment by AlbertoElias** [comment] 2015-03-13 12:36
We released 1.4.3 we should have fixed this. Could you check?

**Comment by roland-vachter** [comment] 2015-03-13 12:56
There is another issue which I reported to you, we'll release the next version once it become stable for our use case.

**Comment by AlbertoElias** [comment] 2015-03-13 13:13
But is this issue fixed? if so, this one should be closed and we can focus on the other one

**Comment by Vallach** [comment] 2015-03-13 13:16
It looks ok on Safari 5, but I'm unable to test on Safari 6 due to a polyfill error when attempting to open the overlay:

Can't find variable: performance
polyfill.min.js:3:1343

Assume this should be raised on the polyfill board and the current issue marked as [blocked]

**Comment by AlbertoElias** [comment] 2015-03-13 13:26
Try to use the non minified polyfill service (remove the '.min' from the url) and report that in the polyfill service repo. Can you test Safari 7 and 8 and mobile?

**Comment by Vallach** [comment] 2015-03-13 13:44
On mobile Safari 8.2 page scrolls down when closing the overlay. It should have maintained the same position.

Note: this is the only version of mobile Safari available to me

**Comment by AlbertoElias** [comment] 2015-03-13 14:03
@Vallach I've tried in mobile safari 8.2 and 7.1 and can't replicate. How are you closing the overlay? If you click the close button, does it work? It might be that you scroll while closing it?

**Comment by Vallach** [comment] 2015-03-13 14:04
The scrolling issue is reproducible in my case by using either Close (x) button or the Cancel button. There is no accidental scrolling involved.

**Comment by AlbertoElias** [comment] 2015-03-13 14:08
Does it happen every time you close it without refreshing the page or just initially?

**Comment by AlbertoElias** [comment] 2015-03-13 14:21
I'm speaking with @Vallach privately to try to reproduce

**Comment by Vallach** [comment] 2015-03-13 14:36
http://jsbin.com/dahujilaka

**Comment by roland-vachter** [comment] 2015-03-13 14:43
It seems the issues is still with the autofocus.

**Comment by AlbertoElias** [comment] 2015-03-13 14:43
Yup =/ Will take a look

**Comment by AlbertoElias** [comment] 2015-03-13 15:12
Update: It only happens the first time you close the overlay like this. I changed your example to have a button run myOverlay.open(); http://jsbin.com/fohija

**Comment by AlbertoElias** [comment] 2015-03-13 15:51
Update #2: This is the same thing I was seeing in my tests, it doesn't exactly scroll to the bottom, if you make the page longer, it doesn't reach the bottom. and the scrolling distance seems to be quite specific and irrelevant to where you position the trigger. I tried moving it to different places, and the scroll always goes to the same height

**Comment by AlbertoElias** [comment] 2015-03-13 16:43
Update 3: It's related to #41 When you close the overlay, the input with autofocus is being focused at that precise point, so the keyboard comes up and scrolls the page

**Comment by AlbertoElias** [comment] 2015-03-13 17:17
Update 4: So it seems autofocus is just buggy in iOS 8: http://stackoverflow.com/questions/26146252/in-ios8-using-focus-will-show-virtual-keyboard-and-scroll-page-after-touch even though [caniuse](http://caniuse.com/#feat=autofocus) says it's not even there. 

The error isn't when closing the overlay but when clicking anywhere on the screen, if you open the overlay and then click the title, it also triggers the keyboard and scrolls the page like issue #41 I'll see if there's a way around it, but if not, either producs don't add autofocus in iOS8, or they just have to understand that that clicking anywhere will trigger the autofocus, but the scrolling issue happens if you click on the input anyway.

What do you think @kaelig @roland-vachter

**Comment by kaelig** [comment] 2015-03-13 17:27
Disable autofocus on iOS altogether.

**Comment by AlbertoElias** [comment] 2015-03-13 17:28
It's only a problem in iOS 8 though and it would be up to products

**Comment by kaelig** [comment] 2015-03-13 17:31
Ok, how about we document this bug in the module's README as a "WONTFIX/Gotcha".

**Comment by AlbertoElias** [comment] 2015-03-13 17:32
I'm investigating a bit more and will document everything in the readme

**Comment by AlbertoElias** [comment] 2015-03-13 17:38
Ok, so autofocus doesn't work in mobile. In chrome you can run .focus() after the page loads, so you could do it when oOverlay.ready is dispatched. In iOS, autofocus will never work, and in iOS8 you can the problem that after the input with autofocus is loaded, and then there's a touchdown event, the focus is activated, so it's quite hard to control. I'm going to add all this to the readme and will check out issue #41 and see if there's a fix for that at least.

**Comment by AlbertoElias** [comment] 2015-03-16 13:08
@roland-vachter So, can this be closed now?

**Comment by roland-vachter** [comment] 2015-03-16 13:10
Yep.

**Closed** 2015-03-16 13:18 UTC
Labels: bug
