### ISSUE TITLE
Close button displayed incorrectly on iPhone

### ISSUE THREAD

**Issue by olizh** [Financial-Times/o-overlay#55] opened 2015-02-09 09:38 UTC
On iPhone mobile safari, iOS 8.1.3. The cross of the close button is not displayed correctly. See screen shot. 
![img_1529](https://cloud.githubusercontent.com/assets/4512113/6103765/6f8f441c-b082-11e4-9ac7-85e1fb64f5f0.PNG)

**Comment by olizh** [comment] 2015-02-09 09:52
It seems to be caused by lack of prefix. These two lines should fix it: 

.o-overlay__close-icon:after, .o-overlay__close-icon:before {
-webkit-transform: translate(-50%,-50%)translate(.75em,.75em);
}

.o-overlay__close-icon {
-webkit-transform: rotate(45deg);
}

**Comment by kaelig** [comment] 2015-02-09 10:45
Thanks for reporting this.

Looks like an issue with autoprefixer not prefixing these properties, which is not normal at all.

@AlbertoElias can you have a look? Is there a test for autoprefixer in the build tools?

**Comment by AlbertoElias** [comment] 2015-02-09 10:55
@olizh Are you using Origami Build Tools to build o-overlay?

**Comment by kaelig** [comment] 2015-02-09 10:58
@AlbertoElias that happens when loading it from the build service.

**Comment by AlbertoElias** [comment] 2015-02-09 11:04
@kaelig Right, I'll take a look

**Comment by Vallach** [comment] 2015-02-09 11:55
Issue also affects:
- IE9 (both Vista and Win7 versions)
- Safari 5.1.10 (OSX 10.6.8)
- Safari 6.1.6 (OSX (10.7.5)
- Safari 8.0.3 (OSX 10.10.2)

Note: 
- cross icon (x) is not centered inside the circle on IE11 Metro
- (x) char is inside a square on IE8 (known issue most probably)

**Comment by kaelig** [comment] 2015-02-09 12:02
Thanks for the thorough testing! Most certainly caused by a autoprefixer issue.

> (x) char is inside a square on IE8 (known issue most probably)

Correct, this is a known and intended degradation.

> cross icon (x) is not centered inside the circle on IE11 Metro

Good catch! It's 1px off, I'll see if I can fix that in a future release.

Here's a selector hack to target IE 11+:

```css
_:-ms-fullscreen, :root .selector {}
```

**Comment by olizh** [comment] 2015-02-10 14:41
@alberto yes I use the build service

**Comment by AlbertoElias** [comment] 2015-03-03 17:24
Hi @olizh. I still need to test IE9, but in Safari it's due to autoprefixer still not running on the build service, this will be sorted out soon

**Comment by AlbertoElias** [comment] 2015-03-04 11:37
Right, I checked in IE9 and it's the same. @samgiles is going to work on adding autoprefixer to the build service, I'll leave this issue open until then

**Comment by samgiles** [comment] 2015-03-05 13:55
Autoprefixer has been added to the build service.  @olizh could you try again? It might take a few hours for the existing cached bundle to expire in Akamai, try a cache buster if you're seeing the same results.

**Comment by kaelig** [comment] 2015-03-09 15:49
Closing, as this works in my tests. Thanks @olizh for reporting this in the first place!

**Closed by kaelig** 2015-03-09 15:49 UTC

**Comment by Vallach** [comment] 2015-03-10 07:49
Is the fixed version released? Looking on Safari in TEST and the icon is still not displayed correctly.

**Comment by AlbertoElias** [comment] 2015-03-10 08:16
Maybe you need to bust the cache. I double checked both IE and Safari and it's definitely working with the registry demos.

**Comment by Vallach** [comment] 2015-03-10 08:27
Definitely NOT working.. used Safari 5, 6, IE9, clean sessions, cache cleared and so on.. Most likely the fixed version is not in the FT Test env

**Comment by AlbertoElias** [comment] 2015-03-10 08:51
What's the build service url you're using for the overlay? As I said, the
issue is fixed in the build service, so we need to look into your
implementation as the cache should have been updated by now. This isn't
related to a release of o-overlay but of the build service, so you
shouldn't need to do anything.

-- 

------------------------------
This email was sent by a company owned by Pearson plc, registered office at 
80 Strand, London WC2R 0RL.  Registered in England and Wales with company 
number 53723.

**Comment by roland-vachter** [comment] 2015-03-10 08:55
Latest release is 1.4.1, 8 days ago.
Is there a new version with this fix because I can't find it in github?

**Comment by AlbertoElias** [comment] 2015-03-10 09:15
Like I said, this has nothing to do with o-overlay, it's a build service
thing, that's why I'm asking for your build service url

-- 

------------------------------
This email was sent by a company owned by Pearson plc, registered office at 
80 Strand, London WC2R 0RL.  Registered in England and Wales with company 
number 53723.

**Comment by roland-vachter** [comment] 2015-03-10 09:17
We are not using the build service, we are including it using bower.
"o-overlay": "^1.1.2"

Then we are building the module with grunt (sass + browserify).

**Comment by AlbertoElias** [comment] 2015-03-10 09:19
Oooooh! Then that's where the error is! You need to run autoprefixer or use
the origami build tools that does it for you :)

-- 

------------------------------
This email was sent by a company owned by Pearson plc, registered office at 
80 Strand, London WC2R 0RL.  Registered in England and Wales with company 
number 53723.

**Comment by roland-vachter** [comment] 2015-03-10 09:19
For FT.com we are using a custom build process, probably would be better to use OBT for this custom build of FT.com..
So is this a configuration issue in the build process?

**Comment by AlbertoElias** [comment] 2015-03-10 09:21
yes, you can check out the sass build process here:
https://github.com/Financial-Times/origami-build-tools/blob/master/lib/tasks/build.js#L108

-- 

------------------------------
This email was sent by a company owned by Pearson plc, registered office at 
80 Strand, London WC2R 0RL.  Registered in England and Wales with company 
number 53723.

**Comment by roland-vachter** [comment] 2015-03-10 09:33
Ok, I'll take a look. Thanks!

**Comment by roland-vachter** [comment] 2015-03-10 09:34
And sorry for misreading your message :)

**Comment by triblondon** [comment] 2015-03-10 10:50
@roland-vachter @Vallach just chiming in here to say we provide two supported solutions for installing origami components: the build service and the Origami build tools.  If you're using one of these and you have a problem with it, we'll try and help as quickly as we can.  You don't have to use either of these, and if you choose to do your own thing, we provide the source code and documentation to help you work out what the build process should be, so we're not against you doing that.  But we don't provide support for that custom build process.  So overall we try and encourage people to use one of the two standard build mechanisms that we do support.

This issue was reported as a problem installing overlay via the build service, and that's definitely resolved, so I'd suggest a fresh issue if you have a problem you can reproduce using the build service or OBT.
